spring.application.name=hardware-stock-api

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/hardware_inventory
spring.datasource.username=postgres
spring.datasource.password=Marquebr

#O Hibernate pega suas entidades Java (@Entity) e sincroniza com o banco.
spring.jpa.hibernate.ddl-auto=update 

#Mostra SQL no terminal.
spring.jpa.show-sql=true

#Formata o SQL para ficar legível.
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_Secret:12345678}